### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by schunlee** [xuzepei/vue#2]
你这个又没服务器交互的，直接就部署在github page了吧，或者就阿里云oss上面，搞台服务器，还容易被人家给攻击呢

**Comment by xuzepei** [comment]
是在github page的。
[https://xuzepei.github.io/vue/](url)

**Comment by xuzepei** [comment]
> 你这个又没服务器交互的，直接就部署在github page了吧，或者就阿里云oss上面，搞台服务器，还容易被人家给攻击呢


是在github page的。
[https://xuzepei.github.io/vue/](url)
